### [dcsxx-commons]
#CXXFLAGS += $(dcs_commons_cflags)
#LDFLAGS += $(dcs_commons_ldflags)
#LDLIBS += $(dcs_commons_ldlibs)

## [fuzzylite]
CXXFLAGS += $(fuzzylite_cflags)
LDFLAGS += $(fuzzylite_ldflags)
LDLIBS += $(fuzzylite_ldlibs)


.PHONY: all clean


all: fuzzylite_version

clean:
	$(RM) fuzzylite_version
